//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FC1_CC.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FC1_CC.Common.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contact your IT admin for permission to view this data..
        /// </summary>
        public static string AdminConsentError {
            get {
                return ResourceManager.GetString("AdminConsentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a App Not Installed.
        /// </summary>
        public static string AppNotInstalled {
            get {
                return ResourceManager.GetString("AppNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Author signature not found on message. Please sign the message..
        /// </summary>
        public static string AuthorNotFound {
            get {
                return ResourceManager.GetString("AuthorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Button Clicks.
        /// </summary>
        public static string ButtonClicks {
            get {
                return ResourceManager.GetString("ButtonClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Button Tracking.
        /// </summary>
        public static string ColumnName_ButtonTracking {
            get {
                return ResourceManager.GetString("ColumnName_ButtonTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delivery Status.
        /// </summary>
        public static string ColumnName_DeliveryStatus {
            get {
                return ResourceManager.GetString("ColumnName_DeliveryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error.
        /// </summary>
        public static string ColumnName_Error {
            get {
                return ResourceManager.GetString("ColumnName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exported By.
        /// </summary>
        public static string ColumnName_ExportedBy {
            get {
                return ResourceManager.GetString("ColumnName_ExportedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Export TimeStamp.
        /// </summary>
        public static string ColumnName_ExportTimeStamp {
            get {
                return ResourceManager.GetString("ColumnName_ExportTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Message Title.
        /// </summary>
        public static string ColumnName_MessageTitle {
            get {
                return ResourceManager.GetString("ColumnName_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reactions.
        /// </summary>
        public static string ColumnName_Reactions {
            get {
                return ResourceManager.GetString("ColumnName_Reactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Read Status.
        /// </summary>
        public static string ColumnName_ReadStatus {
            get {
                return ResourceManager.GetString("ColumnName_ReadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sent TimeStamp.
        /// </summary>
        public static string ColumnName_SentTimeStamp {
            get {
                return ResourceManager.GetString("ColumnName_SentTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status Reason.
        /// </summary>
        public static string ColumnName_StatusReason {
            get {
                return ResourceManager.GetString("ColumnName_StatusReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Team ID.
        /// </summary>
        public static string ColumnName_TeamId {
            get {
                return ResourceManager.GetString("ColumnName_TeamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Team Name.
        /// </summary>
        public static string ColumnName_TeamName {
            get {
                return ResourceManager.GetString("ColumnName_TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UPN.
        /// </summary>
        public static string ColumnName_Upn {
            get {
                return ResourceManager.GetString("ColumnName_Upn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User ID.
        /// </summary>
        public static string ColumnName_UserId {
            get {
                return ResourceManager.GetString("ColumnName_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name.
        /// </summary>
        public static string ColumnName_UserName {
            get {
                return ResourceManager.GetString("ColumnName_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User Type.
        /// </summary>
        public static string ColumnName_UserType {
            get {
                return ResourceManager.GetString("ColumnName_UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} (copy).
        /// </summary>
        public static string DuplicateText {
            get {
                return ResourceManager.GetString("DuplicateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Something went wrong. Try exporting the results again..
        /// </summary>
        public static string ExportFailureText {
            get {
                return ResourceManager.GetString("ExportFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed to create conversation. Error message: {0}.
        /// </summary>
        public static string FailedToCreateConversationFormat {
            get {
                return ResourceManager.GetString("FailedToCreateConversationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed to create conversation with teams user: {0}. Exception: {1}.
        /// </summary>
        public static string FailedToCreateConversationForUserFormat {
            get {
                return ResourceManager.GetString("FailedToCreateConversationForUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed to create conversation. Request throttled. Error message: {0}&quot;.
        /// </summary>
        public static string FailedToCreateConversationThrottledFormt {
            get {
                return ResourceManager.GetString("FailedToCreateConversationThrottledFormt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed to find the team {0} in DB..
        /// </summary>
        public static string FailedToFindTeamInDbFormat {
            get {
                return ResourceManager.GetString("FailedToFindTeamInDbFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed to find the User application: {0} in the organization&apos;s app catalog..
        /// </summary>
        public static string FailedToFindUserAppInAppCatalog {
            get {
                return ResourceManager.GetString("FailedToFindUserAppInAppCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed to sync all users. Status Code: {0} Exception: {1}.
        /// </summary>
        public static string FailedToGetAllUsersFormat {
            get {
                return ResourceManager.GetString("FailedToGetAllUsersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed to get conversation id for user: {0}. Status Code: {1} Exception: {2}.
        /// </summary>
        public static string FailedToGetConversationForUserFormat {
            get {
                return ResourceManager.GetString("FailedToGetConversationForUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed to get members for group {0}: {1}.
        /// </summary>
        public static string FailedToGetMembersForGroupFormat {
            get {
                return ResourceManager.GetString("FailedToGetMembersForGroupFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed to get members for team {0}: {1}.
        /// </summary>
        public static string FailedToGetMembersForTeamFormat {
            get {
                return ResourceManager.GetString("FailedToGetMembersForTeamFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed to install application for user: {0}. Exception: {1}.
        /// </summary>
        public static string FailedToInstallApplicationForUserFormat {
            get {
                return ResourceManager.GetString("FailedToInstallApplicationForUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed to prepare the message for sending:{0}.
        /// </summary>
        public static string FailtoPrepareMessageFormat {
            get {
                return ResourceManager.GetString("FailtoPrepareMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This file contains the results you exported..
        /// </summary>
        public static string FileCardDescription {
            get {
                return ResourceManager.GetString("FileCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The link for this download has expired. Export the results again..
        /// </summary>
        public static string FileCardExpireText {
            get {
                return ResourceManager.GetString("FileCardExpireText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ExportData.
        /// </summary>
        public static string FileName_ExportData {
            get {
                return ResourceManager.GetString("FileName_ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Message_Delivery.
        /// </summary>
        public static string FileName_Message_Delivery {
            get {
                return ResourceManager.GetString("FileName_Message_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Metadata.
        /// </summary>
        public static string FileName_Metadata {
            get {
                return ResourceManager.GetString("FileName_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your file is ready to download. A copy is also available in OneDrive..
        /// </summary>
        public static string FileReadyText {
            get {
                return ResourceManager.GetString("FileReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Something went wrong. Try exporting the results again..
        /// </summary>
        public static string FileUploadErrorText {
            get {
                return ResourceManager.GetString("FileUploadErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Guest.
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Guest User not supported.
        /// </summary>
        public static string GuestUserNotSupported {
            get {
                return ResourceManager.GetString("GuestUserNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Member.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The notification has {0} groups as its recipients. It shouldn&apos;t exceed {1} groups..
        /// </summary>
        public static string NumberOfGroupsExceededLimitWarningFormat {
            get {
                return ResourceManager.GetString("NumberOfGroupsExceededLimitWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The notification has {0} rosters as its recipients. It shouldn&apos;t exceed {1} rosters..
        /// </summary>
        public static string NumberOfRostersExceededLimitWarningFormat {
            get {
                return ResourceManager.GetString("NumberOfRostersExceededLimitWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The notification has {0} teams as its recipients. It shouldn&apos;t exceed {1} teams..
        /// </summary>
        public static string NumberOfTeamsExceededLimitWarningFormat {
            get {
                return ResourceManager.GetString("NumberOfTeamsExceededLimitWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Permission declined. We will not proceed with the export..
        /// </summary>
        public static string PermissionDeclinedText {
            get {
                return ResourceManager.GetString("PermissionDeclinedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recipient Not Found.
        /// </summary>
        public static string RecipientNotFound {
            get {
                return ResourceManager.GetString("RecipientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sent Message.
        /// </summary>
        public static string SentMessage {
            get {
                return ResourceManager.GetString("SentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Succeeded.
        /// </summary>
        public static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Throttled.
        /// </summary>
        public static string Throttled {
            get {
                return ResourceManager.GetString("Throttled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User application not found. Make sure the User app is uploaded to your organization&apos;s app catalog..
        /// </summary>
        public static string UserAppNotFound {
            get {
                return ResourceManager.GetString("UserAppNotFound", resourceCulture);
            }
        }
    }
}
